### PR TITLE
add "Changelog" step from Bitrise with minor improvements

### PR DESCRIPTION
**Pull request by bartekpacia**
It's present in all Bitrise projects I've seen. I think it fits in this repo.

### CODE REVIEW

**Comment by shilangyu** [comment]
Is it ever used outside of bitrise?

**Comment by Albert221** [comment]
@Saancreed's look would be beneficiary, he's well into bash scripts :)

**Comment by bartekpacia** [comment]
@shilangyu no*, but I think having all the code in a single place is... just good.

* I've starting using it in GH Actions in one of my personal projects :P

**Comment by bartekpacia** [comment]
i'm gonna merge it, lets have it checked in

**Pull request merged**
